### ISSUE TITLE
Under python 3.4 constants.py gives an error at import

### ISSUE THREAD

**Issue by dickkniep** [dsoprea/PyInotify#3]
The way octal is used in python3.4 has changed. Now a prefix of 0o needs to be added. 

Python 3.4.0 (default, Jun 19 2015, 14:20:21) 
[GCC 4.8.2] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import inotify.adapters
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/dick/.virtualenvs/cctools/lib/python3.4/site-packages/inotify/adapters.py", line 7, in <module>
    import inotify.constants
  File "/home/dick/.virtualenvs/cctools/lib/python3.4/site-packages/inotify/constants.py", line 3
    IN_CLOEXEC  = 02000000
                         ^
SyntaxError: invalid token

**Comment by Newman101** [comment]
Hi. It looks like a classical "gotcha" with Python. Please have a look at this:

In [1]: 02000000
Out[1]: 524288

In [2]: 00004000
Out[2]: 2048

Basically: In Python, leading zeros do convert the number to octal.

**Comment by Newman101** [comment]
Next question: What are constants IN_CLOEXEC and IN_NONBLOCK supposed to be? Hexadecimal? Decimal?

**Comment by dickkniep** [comment]
As far as I know they should be octal and then they should start with:

 
0o 

 
So if you prepend the current values with 0o it should work. (BTW. there are 4 values affected in constants.py)

If you want I can send you a patch.


Met vriendelijke groet,
Dick Kniep
Lindix BV
tel. 036-5215580
mob. 06-50991858


 
-----Oorspronkelijk bericht-----
Van:Juha <notifications@github.com>
Verzonden:vr 02-10-2015 13:28
Onderwerp:Re: [PyInotify] Under python 3.4 constants.py gives an error at import (#3)
Aan:dsoprea/PyInotify <PyInotify@noreply.github.com>; 
CC:Dick Kniep <dick@lindix.nl>; 
 

Next question: What are constants IN_CLOEXEC and IN_NONBLOCK supposed to be? Hexadecimal? Decimal?

**Comment by paulollivier** [comment]
Hey, thanks for fixing this.

Any idea about when the commit e7476150842adbc8cf5864ece62cdba125b10224 will be in pypi?

**Comment by dsoprea** [comment]
Done.



Dustin
