### ISSUE TITLE
Nose is a requirement?

### ISSUE THREAD

**Issue by SwampFalc** [dsoprea/PyInotify#66]
I wrote some software that uses this module, and I now find myself needing to install that on a machine that has no direct connection to the internet.

So I did what I had been doing so far, namely use `pip` on my dev machine to download all modules and requirements, then upload that to the other machine and install with `pip` from the downloaded wheels.

To my surprise, though, when I downloaded this module, it also downloaded the `nose` module.
A quick check showed that yes indeed, `nose` is listed as a requirement in `inotify/resources/requirements.txt`, yet as I suspected, it isn't used anywhere.

Please remove this requirement as there is no need to have `nose` in a production environment...

**Comment by dsoprea** [comment]
Dropped via cd7b276494d35c1437614cfd2d006948ec7aa015
