### ISSUE TITLE
how is filter_predicate intended to be used?

### ISSUE THREAD

**Issue by erpadmin** [dsoprea/PyInotify#72]
Inotify class function event_gen excerpt:
```
                    for type_name in type_names:
                        if filter_predicate is not None and \
                           filter_predicate(type_name, e) is False:
self.__last_success_return = (type_name, e)
```

its expecting it to be callable?

**Comment by dsoprea** [comment]
Yes. It shows that, no?

You get the type-name and event-info, and need to return a boollean (hence, a predicate).

**Comment by dwvisser** [comment]
I think that, at the very least, the fact that the `filter_predicate` is used to shortcut all event processing should be documented in a detailed docstring for `event_gen()`. Something like what I had to search out in release notes:

> Can now provide `filter_predicate` to event_gen() to allow custom loop termination based on events.
