### ISSUE TITLE
(Minor) Bug in Inotify.remove_watch()

### ISSUE THREAD

**Issue by jamercee** [dsoprea/PyInotify#82]
`remove_watch()` accepts `superficial=False`, but does nothing with it. It looks like the author intended to forward it onto `self.remove_watch_with_id(wd)`.  Not really a big deal, since defaulting to *False* causes it to be removed from the OS event queue. But, it should probably either be passed, or removed from the signature.

**Comment by dsoprea** [comment]
Fixed via 7202fc4f837c90dc676cf638c31fe0312b889fae
