### ISSUE TITLE
Does this project have any active maintainers?

### ISSUE THREAD

**Issue by ryanc-me** [dsoprea/PyInotify#84]
Browsing through the Issues and Pull Requests, I can see quite a few easy-to-fix problems, including PRs that address known issues with well-written patches. However, it seems the last commit was mid-2018.

@dsoprea - how do you feel about adding another maintainer? It would be great to flush a few of these waiting PRs.

Just for reference, this module is:
 - The first result on Google for "python inotify"
 - The first result on PyPI for "inotify"
 - Used by several large open-source projects - [Odoo](https://github.com/odoo/odoo/blob/e565fdb29144e409c330f099d398785a3606d239/odoo/service/server.py#L257), [Yelp's Paasta](https://github.com/Yelp/paasta/blob/51ad1f0865b19a3ecef6dce1950cddad60a6da8c/requirements.txt#L38), [Raspiblitz](https://github.com/rootzoll/raspiblitz/blob/8f3674b4f21921d243c46e1ad282dd95d6714586/home.admin/BlitzTUI/requirements.txt#L3), to name a few.
 - Probably used in many other private projects.

**Comment by dsoprea** [comment]
Yeah. I'm here. Just busy. I'll try to get them out of there.

**Comment by ryanc-me** [comment]
Awesome!

I hope the message above didn't come across the wrong way BTW - it's totally understandable that you're busy, especially given the whole COVID thing, but having another active maintainer would help keep the backlog at bay

**Comment by dsoprea** [comment]
Without you're being involved with this project at all until this point, I'm afraid that I can't accept the offer.
