### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'block_duration_s'

### ISSUE THREAD

**Issue by larvanitis** [dsoprea/PyInotify#9]
A regression was introduced in 0.2.5 in [adapters.py#L33](https://github.com/dsoprea/PyInotify/blame/0.2.5/inotify/adapters.py#L33) and now `adapters.InotifyTree` is broken because it tries to pass `block_duration_s` instead of the _now_ expected `block_duration`.

**Comment by dsoprea** [comment]
Thanks for reporting. Sorry for the inconvenience. PyPI has also been updated.

**Comment by dsoprea** [comment]
Please confirm that your issues are resolved.

**Comment by dsoprea** [comment]
Assuming fixed.
